version: "3"
services:
  mysql_container:
    container_name: mysql_container
    image: mysql
    ports:
      - "${AWS_MYSQL_BINDING_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${AWS_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${AWS_MYSQL_USER}
      - MYSQL_PASSWORD=${AWS_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${AWS_MYSQL_DATABASE}
      - TZ=Asia/Seoul
    volumes:
      - "${AWS_MYSQL_DATA_PATH}:/var/lib/mysql"
      - "${AWS_MYSQL_CUSTOM_CONFIG_PATH}:/etc/mysql/conf.d"
    restart: on-failure

  redis_container:
    container_name: redis_container
    image: redis:latest
    command: ["redis-server", "--requirepass", "${AWS_REDIS_PASSWORD}"]
    ports:
      - "${AWS_REDIS_BINDING_PORT}:6379"
    volumes:
      - "${AWS_REDIS_DATA_PATH}:/data"
      - "${AWS_REDIS_CONFIG_PATH}:/usr/local/conf/redis.conf"
    restart: on-failure

  mongodb_container:
    container_name: mongodb_container
    image: mongo
    ports:
      - "${AWS_MONGO_BINDING_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${AWS_MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${AWS_MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${AWS_MONGO_INITDB_DATABASE}
    volumes:
      - "${AWS_MONGO_DATA_PATH}:/data/db"

  mongodb_express_container:
    image: mongo-express
    container_name: mongodb_express_container
    ports:
      - "${AWS_MONGO_EXPRESS_BINDING_PORT}:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${AWS_MONGO_INITDB_ROOT_USERNAME}:${AWS_MONGO_INITDB_ROOT_PASSWORD}@${AWS_IP_ADDRESS}:${AWS_MONGO_BINDING_PORT}
      - ME_CONFIG_BASICAUTH_USERNAME=${AWS_ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${AWS_ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongodb_container
