spring:
  application:
    name: seatdang
  data:
    mongodb:
      uri: ${MONGO_DB_URI}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      location:

# profile관리
  profiles:
    default: test
  #    active: prodmyseatdangdb

#  # ai api 추가
  openai:
    api:
      key: ${OPENAI_API_KEY}


  #  thymeleaf:
#    thymeleaf:
#      cache:false


#    prefix: classpath:/templates/
#    suffix: .html

# NCP
#  s3:
#    accessKey: ${SPRING_S3_ACCESSKEY}
#    secretKey: ${SPRING_S3_SECRETKEY}
#    bucket: myseatdang-bucket2

# AWS용
  s3:
    accessKey: ${AWS_ACCESS_KEY_ID}  # AWS IAM 사용자의 Access Key ID
    secretKey: ${AWS_SECRET_ACCESS_KEY}  # AWS IAM 사용자의 Secret Key
    bucket: myseatdang-bucket2  # AWS S3 버킷 이름
    region: ap-northeast-2  # 서울 리전



#OAUTH - NAVER
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${OAUTH2_NAVER_CLIENT_ID}
            client-secret: ${OAUTH2_NAVER_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,nickname,mobile
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    root: info
    com.matdang.seatdang: debug
    org.hibernate.SQL: debug


app:
  version: 0.1.1

#file:
#  upload-dir: /path/to/upload/directory

file:
  upload-dir: ""

#ncp:
#  api:
#    accessId: ${NCP_APIGW_ACCESS_ID}
#    secretKey: ${NCP_APIGW_SECRET_KEY}

